# This file contains the credentials for the voice & chat platforms
# which your bot is using.
# https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels/

rest:
#  # you don't need to provide anything here - this channel doesn't
#  # require any credentials


#facebook:
#  verify: "Pleoticus"
#  secret: "e4590ff76a688b16516b720236670a62"
#  page-access-token: "EAAG09UGKAtMBAJbovvE6SqzOT5D4CSZCGEPZALGKKzNcgm6vLFzQZCspqfGsQLPZCgZCUsFYqZAQm5BgMmdEpwIHQmyv03CtQSZBajG1FKnNqhSrLKZAiqp5KnyOKGXnIUrPc8hN4mAtqEnHM5C6yvNVtmAuThqCM2JxYkFlTnXDNwZDZD"

twilio:
  account_sid: "AC8ee72ba2caa8f84894d8d1c9da653bcb"
  auth_token: "a239e12a67a1d1b102f7791c6dcf7602"
  twilio_number: "whatsapp:+14155238886"


telegram:
  access_token: "1459379148:AAHKJIZ0LyKuVyLUxmn5TiykebixmiUQ0p4"
  verify: "Pleoticus_bot"
  webhook_url: "https://asistente-facebook.herokuapp.com/webhooks/telegram/webhook"  

#slack:
#  slack_token: "<your slack token>"
#  slack_channel: "<the slack channel>"

#socketio:
#  user_message_evt: <event name for user message>
#  bot_message_evt: <event name for but messages>
#  session_persistence: <true/false>

#mattermost:
#  url: "https://<mattermost instance>/api/v4"
#  token: "<bot token>"
#  webhook_url: "<callback URL>"

# This entry is needed if you are using Rasa X. The entry represents credentials 
# for the Rasa X "channel", i.e. Talk to your bot and Share with guest testers.
rasa:
  url: "http://localhost:5002/api"
